In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../Dataset/customer_shopping_behavior.csv')

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [12]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [13]:
 df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [14]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [16]:
df.groupby('Category')['Review Rating'].median()

Category
Accessories    3.8
Clothing       3.7
Footwear       3.8
Outerwear      3.8
Name: Review Rating, dtype: float64

In [19]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [20]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [21]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [23]:
df = df.rename(columns ={'purchase_amount_(usd)':'purchase_amount'})

In [24]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [25]:
#create a columns age_group
labels = ['Young Adult' , 'Adult', 'Middle-aged', 'Senior']
df['Age_group'] =pd.qcut(df['age'] , q=4, labels= labels)

In [28]:
df[['age', 'Age_group']].head()

   age    Age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged

In [30]:
# create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly' :30,
    'Quarterly' : 90,
    'Bi-Weekly':14,
    'Annually' :365,
    'Every 3 Months' : 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [32]:
df[['purchase_frequency_days']].head()

   purchase_frequency_days
0                       14
1                       14
2                        7
3                        7
4                      365

In [35]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [36]:
df = df.drop('promo_code_used', axis=1)

In [37]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'Age_group', 'purchase_frequency_days'],
      dtype='object')

In [38]:
pip install psycopg2.binary sqlalchemy

Collecting psycopg2.binaryNote: you may need to restart the kernel to use updated packages.

  Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\armaa\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\armaa\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\armaa\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 588.2 kB/s eta 0:00:04
   ----------- ---------------------------- 0.8/2.7 MB 711.4 kB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.7 MB 711.4 kB/s eta 0:00:03
   --------------- ------------------------ 1.0/2.7 MB 766.3 kB/s eta 0:00:03
   --------------- ------------------------ 1.0/2.7 MB 766.3 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.7 MB 708.1 kB/s eta 0:00:02
   ----------------------- ---------------- 1.6/2.7 MB 695.7 kB/s eta 0:00:02
   ----------------------- ---------------- 1.6/2.7 MB 695.7 kB/s eta 0:00:02
   ----------------------- ---------------- 1.6/2.7 MB 695.7 kB/s eta 0:00:02
   --------------------------- ------------ 1.8/2.7 MB 642.5 kB/s eta 0:00:02
   --------------------------- ------------ 1.8/2.7 MB 642.5 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.7 MB 627.9 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.7 MB 646.5 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.7 MB 646.5 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 646.4 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 646.4 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 646.4 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 646.4 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 646.4 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 646.4 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 646.4 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 646.4 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 646.4 kB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 425.4 kB/s eta 0:00:00
Installing collected packages: psycopg2.binary
Successfully installed psycopg2.binary-2.9.11

In [44]:
#step 1 : Connect to PostgreSQL

from sqlalchemy import create_engine
import urllib.parse
username ='postgres'
password = 'Arm123@#'

encoded_password = urllib.parse.quote_plus(password)

host ='localhost'
port= '5432'
database= 'customer_shopping_behaviour'

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name ="customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

OperationalError: (psycopg2.OperationalError) could not translate host name "#@localhost" to address: Non-recoverable failure in name resolution

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [45]:
#step 1 : Connect to PostgreSQL

from sqlalchemy import create_engine
import urllib.parse

username = 'postgres'
password = 'Arm123@#'  # Password with special characters
# URL encode the password to handle special characters
encoded_password = urllib.parse.quote_plus(password)

host = 'localhost'
port = '5432'
database = 'customer_shopping_behaviour'

# Use the encoded password in the connection string
engine = create_engine(f"postgresql+psycopg2://{username}:{encoded_password}@{host}:{port}/{database}")

# Make sure df is defined before this line
# If df is not defined, you need to create or load it first
table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_shopping_behaviour'.

In [46]:
import psycopg2

try:
    conn = psycopg2.connect(
        host="localhost",
        database="postgres",
        user="postgres",
        password="Arm123@#",
        port="5432"
    )
    print("✅ Connected successfully")
except Exception as e:
    print("❌ Error:", e)

✅ Connected successfully